import os
import datetime

# File to store data
DATA_FILE = "health_tracker_data.txt"

# Function to log data
def log_activity():
    date = input("Enter the date (YYYY-MM-DD): ")
        steps = int(input("Steps walked: "))
            calories = float(input("Calories burned: "))
                water = float(input("Water intake (liters): "))
                    sleep = float(input("Sleep hours: "))
                        
                            with open(DATA_FILE, "a") as file:
                                    file.write(f"{date},{steps},{calories},{water},{sleep}\n")
                                        
                                            print("\n✅ Activity logged successfully!")

                                            # Function to display logged data
                                            def display_data():
                                                if not os.path.exists(DATA_FILE):
                                                        print("\nNo data found!")
                                                                return
                                                                    
                                                                        print("\n--- Logged Data ---")
                                                                            with open(DATA_FILE, "r") as file:
                                                                                    for line in file:
                                                                                                date, steps, calories, water, sleep = line.strip().split(",")
                                                                                                            print(f"Date: {date}, Steps: {steps}, Calories: {calories}, Water: {water}L, Sleep: {sleep} hrs")

                                                                                                            # Function to generate summary
                                                                                                            def generate_summary():
                                                                                                                if not os.path.exists(DATA_FILE):
                                                                                                                        print("\nNo data found!")
                                                                                                                                return
                                                                                                                                    
                                                                                                                                        total_steps = 0
                                                                                                                                            total_calories = 0
                                                                                                                                                total_water = 0
                                                                                                                                                    total_sleep = 0
                                                                                                                                                        days = 0
                                                                                                                                                            
                                                                                                                                                                with open(DATA_FILE, "r") as file:
                                                                                                                                                                        for line in file:
                                                                                                                                                                                    days += 1
                                                                                                                                                                                                _, steps, calories, water, sleep = line.strip().split(",")
                                                                                                                                                                                                            total_steps += int(steps)
                                                                                                                                                                                                                        total_calories += float(calories)
                                                                                                                                                                                                                                    total_water += float(water)
                                                                                                                                                                                                                                                total_sleep += float(sleep)
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                        print("\n--- Summary ---")
                                                                                                                                                                                                                                                            print(f"Total Days Tracked: {days}")
                                                                                                                                                                                                                                                                print(f"Total Steps: {total_steps}")
                                                                                                                                                                                                                                                                    print(f"Total Calories Burned: {total_calories:.2f}")
                                                                                                                                                                                                                                                                        print(f"Average Water Intake: {total_water/days:.2f}L/day")
                                                                                                                                                                                                                                                                            print(f"Average Sleep Hours: {total_sleep/days:.2f} hrs/day")

                                                                                                                                                                                                                                                                            # Main menu
                                                                                                                                                                                                                                                                            def main_menu():
                                                                                                                                                                                                                                                                                while True:
                                                                                                                                                                                                                                                                                        print("\n=== Health & Fitness Tracker ===")
                                                                                                                                                                                                                                                                                                print("1. Log Activity")
                                                                                                                                                                                                                                                                                                        print("2. Display Logged Data")
                                                                                                                                                                                                                                                                                                                print("3. Generate Summary")
                                                                                                                                                                                                                                                                                                                        print("4. Exit")
                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                        choice = input("Enter your choice: ")
                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                        if choice == "1":
                                                                                                                                                                                                                                                                                                                                                                    log_activity()
                                                                                                                                                                                                                                                                                                                                                                            elif choice == "2":
                                                                                                                                                                                                                                                                                                                                                                                        display_data()
                                                                                                                                                                                                                                                                                                                                                                                                elif choice == "3":
                                                                                                                                                                                                                                                                                                                                                                                                            generate_summary()
                                                                                                                                                                                                                                                                                                                                                                                                                    elif choice == "4":
                                                                                                                                                                                                                                                                                                                                                                                                                                print("\nThank you for using the Health & Fitness Tracker!")
                                                                                                                                                                                                                                                                                                                                                                                                                                            break
                                                                                                                                                                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("\nInvalid choice. Please try again.")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Run the program
                                                                                                                                                                                                                                                                                                                                                                                                                                                                if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    main_menu()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    